
<!DOCTYPE html>
<html lang="en">
<head>
    <!--
------------------------------------------------------------------------------------------
COMP1230 -  Assignment 1
------------------------------------------------------------------------------------------
Objective: To create a simple PHP application using a flat file (no database).
For this project, you will be creating an application called CONTACT. The application is for personal use.

Operations:
The user must be able to perform the following operations:
1. list contacts (show first, last name, picture and modify and delete links in a table)
2. edit contact by clicking on modify link in the contacts list
3. deleting a contact by clicking on delete link in the contact list (use javascript to confirm the
deletion)
4. search for a contact by the first name and/or last name
5. Create a new contact.

****************************************************************************************
         File with HTML and PHP -
         Operation 3 - Deleting a contact by clicking on delete link in the contact list
         (use javascript to confirm the deletion)
****************************************************************************************

-->
<meta charset="UTF-8">
<meta name="keywords" content="PHP, Assignment, Comp1230">
<meta name="author" content="Renata Moura">
<meta name="description" content="PHP Assignment">
<meta charset="UTF-8">

<!-- CSS style -->
    <link rel="stylesheet" href="style.css">

</head>


<body>

<header>
    <h1>Delete Contacts</h1>
</header>

<?php
/**
 * Created by PhpStorm.
 * User: Renata
 * Date: 2017-12-08
 * Time: 10:55 AM
 */

include "functions.php";

/*
====================================================
    Call function delete contact
====================================================
 */
if(isset($_POST['BTDelete'])) {
    $id = @$_POST['BTDelete'];
    delete();
}
?>
<footer>
    <!--View Source link -->
    <a href="/folder_view/vs.php?s=<?php echo __FILE__?>" target="_blank">View Source</a>
</footer>

</body>

</html>

